@startuml
scale 800 height
skinparam BackgroundColor #EEEBDC

' 2. Диаграмма классов
class Пользователь {
  -логин : строка
  -пароль : строка
  +войти() : булево
  +выйти()
}

class Администратор {
  +создатьПользователя()
}


Пользователь::войти -right-> Администратор::создатьПользователя

@endum
